export const mockPaymentsData = [
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Pending Confirmation",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Overdue",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Overdue",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Paid",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Paid",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Paid",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Paid",
    date: "Feb 1, 2025",
  },
  {
    invoice: "INV-104",
    amount: "#250, 000",
    project: "Food Delivery Website",
    milestone: "Wireframe Design",
    status: "Paid",
    date: "Feb 1, 2025",
  },
];
